# Stage-specific configurations

spring:
  datasource:
    url: jdbc:postgresql://lsu-comet-11289.6wr.aws-us-west-2.cockroachlabs.cloud:26257/LSU?sslmode=verify-full
    username: stage_user
    password: stage_password  # Replace with the actual password
  application:
    name: LSU-Game-Room-RevOps-Nexus-Stage
